server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .jsp
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/visionarycrofting
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: false